from app.code import sumOfTwoNumbers

def test_success_sumOfTwoNumbers():
    assert (5 == sumOfTwoNumbers(2, 3)), "Test case failed!"